name: Build Python and Release Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  build-windows-installer:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Run PyInstaller
        run: |
          python -m PyInstaller src/get_from_direwolf.py
      - uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: dist/get_from_direwolf
      - name: Get PR number from merge commit
        id: get_pr_number
        run: |
          PR_NUMBER=$(echo "${{ github.event.head_commit.message }}" | grep -oE "#[0-9]+" | grep -oE "[0-9]+")
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ github.sha }}
          name: Release for PR ${{ steps.get_pr_number.outputs.pr_number }}
          files: path/to/your/artifact.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.get_pr_number.outputs.pr_number != ''
