name: Build Python and Release Executable

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build-windows-installer:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Run PyInstaller
        run: |
          python -m PyInstaller src/get_from_direwolf.py
      - uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: src/dist/main
      - name: Upload Release Artifact
        uses: Vucko130/upload-release-action@2.5.4
        with:
          file: release.zip
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          overwrite: true
          release_name: v1.0
