name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Create .aws directory at project root
      run: mkdir -p .aws
    
    - name: Create credentials & config files
      run: |
        echo ${{secrets.AWS_CREDENTIALS}} > .aws/credentials
        echo "[Default]\nregion = us-east-2" > .aws/config



    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
    
    - name: Run tests
      run: |
        python tests/run_tests.py
